version: '3'

services:
  sqlserver:
    image: microsoft/mssql-server-linux:latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P24d!dBX!qRf
      - MSSQL_PID=Express
    ports:
      - "1434:1433"
